"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class c_test_lcmt(object):
    __slots__ = ["body_pos", "body_ori"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [[3], [3]]

    def __init__(self):
        self.body_pos = [ 0.0 for dim0 in range(3) ]
        self.body_ori = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(c_test_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.body_pos[:3]))
        buf.write(struct.pack('>3f', *self.body_ori[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != c_test_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return c_test_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = c_test_lcmt()
        self.body_pos = struct.unpack('>3f', buf.read(12))
        self.body_ori = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if c_test_lcmt in parents: return 0
        tmphash = (0xbc9c850443fb3b27) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if c_test_lcmt._packed_fingerprint is None:
            c_test_lcmt._packed_fingerprint = struct.pack(">Q", c_test_lcmt._get_hash_recursive([]))
        return c_test_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

