/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class c_test_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] body_pos;
        public float[] body_ori;
 
        public c_test_lcmt()
        {
            body_pos = new float[3];
            body_ori = new float[3];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xbc9c850443fb3b27L;
 
        static c_test_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.c_test_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.c_test_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 3; a++) {
                outs.Write(this.body_pos[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.body_ori[a]); 
            }
 
        }
 
        public c_test_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public c_test_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.c_test_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.c_test_lcmt o = new LCMTypes.c_test_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.body_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.body_pos[a] = ins.ReadSingle();
            }
 
            this.body_ori = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.body_ori[a] = ins.ReadSingle();
            }
 
        }
 
        public LCMTypes.c_test_lcmt Copy()
        {
            LCMTypes.c_test_lcmt outobj = new LCMTypes.c_test_lcmt();
            outobj.body_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.body_pos[a] = this.body_pos[a];
            }
 
            outobj.body_ori = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.body_ori[a] = this.body_ori[a];
            }
 
            return outobj;
        }
    }
}

